name: Build and Push Docker Image with ARC (Buildah)

on: [push]

env:
  # Define image name (adjust if needed)
  IMAGE_NAME: ${{ github.repository }} # Uses repo name like 'owner/repo'

jobs:
  build:
    # IMPORTANT: Ensure this job runs on runners managed by the ARC
    # deployment/set where dockerEnabled: true is configured.
    # Use labels defined in your RunnerDeployment/RunnerSet.
    runs-on: arc-runner-set # Adjust label as needed

    permissions:
      contents: read
      packages: write # Needed for ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        # Buildah uses Podman's auth file, so podman-login works
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with Buildah
        uses: redhat-actions/buildah-build@v2
        id: buildah # Give the step an ID to potentially access outputs
        with:
          # Base image name (uses owner/repo format from env var)
          image: ${{ env.IMAGE_NAME }}
          # Registry where the image is pushed (lowercase owner required for GHCR)
          registry: ghcr.io/${{ github.repository_owner }}
          # Tags for the image (e.g., latest and git sha)
          tags: "latest ${{ github.sha }}"
          # Path to the Dockerfile (use 'containerfiles' if you prefer that name)
          dockerfiles: |
            ./Dockerfile
          # Build context directory
          context: .
          # Push the image to the registry after building
          push: true
          # Optional: Add build arguments if needed
          # build-args: |
          #   MY_ARG=value

      # Optional: Print image details
      - name: Print image details
        run: |
          echo "Image pushed: ${{ steps.buildah.outputs.image }}:${{ steps.buildah.outputs.tags }}"
          echo "Full Image URL: ${{ steps.buildah.outputs.image-with-tag }}" # Usually includes the first tag