name: Build and Push Docker Image with ARC (Buildah)

on: [push]

env:
  # Define image name (adjust if needed)
  IMAGE_NAME: ${{ github.repository }} # Uses repo name like 'owner/repo'

jobs:
  build:
    # IMPORTANT: Ensure this job runs on runners managed by the ARC
    # deployment/set where dockerEnabled: true is configured.
    # Use labels defined in your RunnerDeployment/RunnerSet.
    runs-on: arc-runner-set # Adjust label as needed

    permissions:
      contents: read
      packages: write # Needed for ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman and Buildah
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman buildah
        # Note: Use 'sudo' if the runner doesn't run as root.
        # Adjust package manager commands if using a different base image (e.g., yum/dnf for RHEL/Fedora)




       # --- Use sudo for Podman/Buildah commands ---
      - name: Log in to GitHub Container Registry (as root)
        run: sudo podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Build Docker image with Buildah (as root)
        id: buildah
        run: |
          sudo buildah bud \
            --tag ${{ env.IMAGE_REGISTRY_PATH }}:latest \
            --tag ${{ env.IMAGE_REGISTRY_PATH }}:${{ github.sha }} \
            -f ./Dockerfile .
          # Output the image name/tag for potential later steps (optional)
          echo "image-with-tag=${{ env.IMAGE_REGISTRY_PATH }}:latest" >> $GITHUB_OUTPUT

      - name: Push Docker image with Buildah (as root)
        run: |
          sudo buildah push ${{ env.IMAGE_REGISTRY_PATH }}:latest
          sudo buildah push ${{ env.IMAGE_REGISTRY_PATH }}:${{ github.sha }}

      # Optional: Print image details
      - name: Print image details
        run: |
          echo "Image pushed: ${{ steps.buildah.outputs.image-with-tag }}"